apiVersion: v1
kind: Pod
metadata:
  name: svc-pod 
  labels:
    app: test-1
spec:
  containers: 
    - name: test-co 
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP