apiVersion: v1
kind: Pod
metadata:
  name: jenkins-utilization
  labels:
    app: jenkins-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-alpine
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0       # run as root to install tools like 'stress'
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "300Mi"
          cpu: "200m"
        limits:
          memory: "600Mi"
          cpu: "500m"
  restartPolicy: Alwaysd