apiVersion: v1
kind: Pod
metadata:
  name: jenkins-utilization
  labels:
    app: mytest-pod
spec:
  containers:
    - name: mytest-container
      image: jenkins/jenkins:lts-alpine
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0   
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "300m"
  restartPolicy: Always


